name: Build docker image and publish
on:
  push:
    branches: [master]
  schedule:
    # build and publish a new base image every week at 04:17am on mondays
    - cron: "17 04 * * 1"
env:
  BASE_IMAGE_NAME: base-docker
  ACTION_IMAGE_NAME: base-action
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build image
      run: make clean-build
    - name: Run tests
      run: make test
    - name: Run lint
      run: make lint
    - name: Log into GitHub Container Registry
      run: echo ${{ secrets.DOCKER_RW_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to GitHub Container Registry
      run: |
        BASE_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$BASE_IMAGE_NAME
        ACTION_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$ACTION_IMAGE_NAME
        docker tag $BASE_IMAGE_NAME $BASE_IMAGE_ID:latest
        docker tag $ACTION_IMAGE_NAME $ACTION_IMAGE_ID:latest
        docker push $BASE_IMAGE_ID:latest
        docker push $ACTION_IMAGE_ID:latest
